server:
  port: ${SERVER_PORT:${PORT:8085}}
spring:
  profiles:
    default: local
  application:
    name: notification-service
  datasource:
    url: ${DATABASE_URL:${NOTIFICATION_DB_URL:jdbc:mysql://localhost:3306/payment_notification_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}}
    username: ${DATABASE_USERNAME:${MYSQL_USER:root}}
    password: ${DATABASE_PASSWORD:${MYSQL_PASSWORD:root123}}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.nitin.payment.common.event
eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
app:
  kafka:
    enabled: ${KAFKA_ENABLED:false}
  redis:
    enabled: ${REDIS_ENABLED:false}
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
