eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    register-with-eureka: true
    fetch-registry: true

app:
  kafka:
    enabled: ${KAFKA_ENABLED:false}
  redis:
    enabled: ${REDIS_ENABLED:false}

