spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/fraud_db}

eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}
    register-with-eureka: false
    fetch-registry: false

app:
  kafka:
    enabled: ${KAFKA_ENABLED:false}
  mongodb:
    enabled: ${MONGODB_ENABLED:false}
  redis:
    enabled: ${REDIS_ENABLED:false}
