spring:
  datasource:
    url: ${TRANSACTION_DB_URL:jdbc:mysql://localhost:3306/payment_transaction_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root123}

eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    register-with-eureka: true
    fetch-registry: true

app:
  kafka:
    enabled: ${KAFKA_ENABLED:false}
  redis:
    enabled: ${REDIS_ENABLED:false}

